; Please do not edit this file! If this file is modified, results are unpredictable.
; Instead of modifying this file, simply create a new MEGA Analysis Options file by using the MEGA Prototyper.
[ MEGAinfo ]
ver                                      = 7150910-x86_64 Mac OS                   
[ DataSettings ]
datatype                                 = snNucleotide                            
containsCodingNuc                        = True                                    
MissingBaseSymbol                        = ?                                       
IdenticalBaseSymbol                      = .                                       
GapSymbol                                = -                                       
[ ProcessTypes ]
ppDistEst                                = true                                    
ppWithinGpAvg                            = true                                    
[ AnalysisSettings ]
Analysis                                 = Distance Estimation                     
Scope                                    = Between group average                    
Estimate Variance                        = ====================                    
Variance Estimation Method               = None                                    
No. of Bootstrap Replications            = Not Applicable                          
Substitution Model                       = ====================                    
Substitutions Type                       = Nucleotide                              
Model/Method                             = p-distance                              
Fixed Transition/Transversion Ratio      = Not Applicable                          
Substitutions to Include                 = d: Transitions + Transversions          
Rates and Patterns                       = ====================                    
Rates among Sites                        = Gamma Distributed (G)                   
Gamma Parameter                          = 0.50                                    
Pattern among Lineages                   = Same (Homogeneous)                      
Data Subset to Use                       = ====================                    
Gaps/Missing Data Treatment              = Partial deletion                        
Site Coverage Cutoff (%)                 = 50                                      
Select Codon Positions                   = 1st, 2nd, 3rd, Non-Coding               
Genetic Code Table                       = Not Applicable                          
Genetic Code                             = Not Applicable                          
Has Time Limit                           = False                                   
Maximum Execution Time                   = -1                                      
