; Please do not edit this file! If this file is modified, results are unpredictable.
; Instead of modifying this file, simply create a new MEGA Analysis Options file by using MEGA.
[ MEGAinfo ]
ver                                      = 10200107-x86_64 MS Windows              
[ DataSettings ]
datatype                                 = snNucleotide                            
containsCodingNuc                        = True                                    
MissingBaseSymbol                        = ?                                       
IdenticalBaseSymbol                      = .                                       
GapSymbol                                = -                                       
Labelled Sites                           = All Sites                               
Labels to Include                        =                                         
[ ProcessTypes ]
ppDistEst                                = true                                    
ppBetweenGpAvg                           = true                                    
[ AnalysisSettings ]
Analysis                                 = Distance Estimation                     
Scope                                    = Between group average                   
Estimate Variance                        = ====================                    
Variance Estimation Method               = None                                    
No. of Bootstrap Replications            = Not Applicable                          
Substitution Model                       = ====================                    
Substitutions Type                       = Nucleotide                              
Model/Method                             = Maximum Composite Likelihood            
Fixed Transition/Transversion Ratio      = Not Applicable                          
Substitutions to Include                 = d: Transitions + Transversions          
Rates and Patterns                       = ====================                    
Rates among Sites                        = Uniform Rates                           
Gamma Parameter                          = Not Applicable                          
Pattern among Lineages                   = Same (Homogeneous)                      
Data Subset to Use                       = ====================                    
Gaps/Missing Data Treatment              = Pairwise deletion                       
Site Coverage Cutoff (%)                 = Not Applicable                          
Select Codon Positions                   = 1st, 2nd, 3rd, Non-Coding               
Genetic Code Table                       = Not Applicable                          
Genetic Code                             = Not Applicable                          
Has Time Limit                           = False                                   
Maximum Execution Time                   = -1                                      
